server:
  port: 8081
spring:
  datasource:
    username: root
#    password: root
#    password: iinh@lcg_mysql@321
#    url: jdbc:mysql://123.57.225.189:7306/blog?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: guoshengkai373
    url: jdbc:mysql://8.142.70.6:4407/blog?serverTimezone=UTC
  freemarker:
    cache: false
    charset: utf-8
    suffix: .ftl
mybatis:
  mapper-locations: classpath:/mappers/*.xml
logging:
  level:
    com.aiyi.blog: DEBUG
  file:
    name: logs/blog.log
